# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a620b723c6ee2abc656287633d565b7a139a22d699ba5e408a2715f76b7d398d9d4fe2d2f7c309ee154b6668a9d22f554c4a7f205192ef62eba88298bd77355f

test:
  secret_key_base: c43132c02821e7cb0776551e6680d41006a31f0bb668a274a781b2c841848dbaa03531214ad09b3b98d2a7f27604e66a2e5895bae20336010e14122df36dc4af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
